### PR TITLE
[c/c++ modes] Allow character literals to contain non-BMP codepoints.

### PR DESCRIPTION
**Pull request by zetafunction**
Character literals such as U'🌌' confuse the current grammar. This is
probably because 🌌 is internally represented as multiple UTF-16
characters. Relax the grammar for character literals to allow matching
zero or more character units between a pair of single quotation marks.

### CODE REVIEW

**Comment by zetafunction** [comment]
Sorry, I'm new to this process: I ran `npm install` to update `dist`, and I saw a number of surprising and unexpected diffs. Is there a better way to update those files?

**Comment by marijnh** [comment]
I think you ended up with a different Rollup version, producing slightly different output.

So that should be harmless. But I'm not seeing any changes in src/ in the patch. Did something go wrong?

**Comment by zetafunction** [comment]
Sorry about that, I'm not sure why the .grammar change got reverted before sending the PR. I think I've fixed it now.

**Comment by marijnh** [comment]
Thanks. I've merged this in eb6a9b942df873347f and upgraded Rollup in 096ebf9d77da51fdc7ba so that the unexpected dist/ changes issue shouldn't happen for the next person.

**Pull request closed without merging**
