### PR TITLE
Added a mode for CLIF

### PR DESCRIPTION
**Pull request by superbobry**
CLIF is a tool for exposing C++ code to various languages via auto-generated wrappers. This PR adds a mode for PyCLIF, a Python dialect implemented in [google/clif](https://github.com/google/clif).

The implementation is based on the [pyparsing grammar](https://github.com/google/clif/blob/87eed3999dba9f8d160c6b735e1803640d019289/clif/python/pytd_parser.py.).

Note that the mode does not currently support folding.

### CODE REVIEW

**Comment by superbobry** [comment]
I'd be keen to add indentation-based code folding, but the Demo HTML doesn't seem to show the fold arrow in the gutter (see screenshot). 

image

**Comment by superbobry** [comment]
@marijnh Thanks for merging this! Do you have any pointers on how I could enable fold icons in the gutter locally?

**Comment by marijnh** [comment]
You'll want the [foldgutter addon](https://codemirror.net/doc/manual.html#addon_foldgutter).

**Comment by superbobry** [comment]
Sure, the problem is that it's already included and enabled in `index.html`, yet there're no gutter icons nor markup in the DOM for neither of the languages.

https://github.com/codemirror/google-modes/blob/4af3267d3313d7a28ce3321505056d030032691d/index.html#L36-L36

https://github.com/codemirror/google-modes/blob/4af3267d3313d7a28ce3321505056d030032691d/index.html#L940-L941

**Comment by marijnh** [comment]
Ah, seems those were just blanked-enabled in e1adcf76 without actually loading the relevant style sheets. Patch 8b68488 should help.

**Comment by superbobry** [comment]
Awesome, thank you so much!

**Pull request merged**
